### ISSUE TITLE
removing missing images?

### ISSUE THREAD

**Issue by poliver1** [sivaschenko/magento2-clean-media#2]
is there a way to remove missing images?

i can't seem to run catalog:images:resize cause there's a few missing images after transferring site contents from opencart. and it's quite a pain trying to locate those products only having image link.

thank you

**Comment by backendorf** [comment]
Hi @kewne2003, I had the same problem, and managed to get around as follows:
1st Run "bin / magento si: catalog: media -m"
2nd Copy missing files and paste into Sublime Text 3
3rd select .png and hold down Ctrl + d until you select all records and add "DELETE FROM catalog_product_entity_media_gallery WHERE value =" in front of them all.
4th run on database.
Seria bom se tivesse um comando que faz isso...
Att

**Comment by peterjaap** [comment]
I created a PR to add this to the extension; https://github.com/sivaschenko/magento2-clean-media/pull/8

Before;

```
$ bin/magento si:catalog:media -m -o

Missing media files:
... long list of files...
Media Gallery entries: 65235.
Files in directory: 18548.
Cached images: 687.
Unused files: 718.
Missing files: 8931.
```

After:

```
$ bin/magento si:catalog:media -m

Missing media files:

Media Gallery entries: 56304.
Files in directory: 18548.
Cached images: 687.
Unused files: 718.
Missing files: 0.
```

**Comment by sivaschenko** [comment]
https://github.com/sivaschenko/magento2-clean-media/pull/8 merged
