### ISSUE TITLE
Class Sivaschenko\CleanMedia\Command\CatalogMedia does not exist

### ISSUE THREAD

**Issue by ilamp** [sivaschenko/magento2-clean-media#3]
After install I can't run the setup:upgrade command. I get following error:

`In ClassReader.php line 19:

  Class Sivaschenko\CleanMedia\Command\CatalogMedia does not exist`

**Comment by ikslavok** [comment]
If anyone has the same problem, just download these files and put it into app/code/Sivaschenko/CleanMedia

**Comment by sivaschenko** [comment]
Fixed in https://github.com/sivaschenko/magento2-clean-media/pull/1
