### ISSUE TITLE
Cant intall in MC 2.3.2

### ISSUE THREAD

**Issue by alfredogama** [sivaschenko/magento2-clean-media#4]
Hello, 
I got this message:

 [InvalidArgumentException]                                                   
Could not find a version of package sivaschenko/magento2-clean-media matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

**Comment by axander44** [comment]
Try with this command:
composer require sivaschenko/magento2-clean-media:dev-master

**Comment by sivaschenko** [comment]
Thanks for reporting! 1.0.0 initial release was added to the repository.
